//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sharm.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderService = new HashSet<OrderService>();
        }
    
        public int Id { get; set; }
        public int ClientId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public int Accepted { get; set; }

        string ServiceAll { get
            {
                string str = "";
                foreach (var item in OrderService)
                {
                    str += item.Service.Name + ", ";
                }
                return str;
            }
        }
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderService> OrderService { get; set; }
    }
}
